<?php

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;
class GoodsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('goods')->insert([
            [
                'user_id' => 1,
                'username' => '舒婷',
                'shop_id' => 1,
                'shop_name' => '至尊披萨（东圃店）',
                'shop_address' => '天河区东圃大马路36号',
                'good_name' => '10英寸榴莲披萨（爆款）',
                'commodity_price' => 40,
                'category_id' => 1,
                'cate_name' => '美食',
                'type' => 1,
                'selling_price' => 39.9,
                'good_integral' => 0,
                'attribute_id' => 4,
                'limit_num' => 2,
                'total_stock' => 300,
                'selling_num' => 50,
                'state' => 1,
                'order' => 50,
                'good_image' => 'http://img5.imgtn.bdimg.com/it/u=1218344908,2950045501&fm=26&gp=0.jpg',
                'detail_image' => 'http://img3.imgtn.bdimg.com/it/u=2136448882,2820293373&fm=26&gp=0.jpg',
                'description' => '购买须知描述',
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                'user_id' => 1,
                'username' => '舒婷',
                'shop_id' => 1,
                'shop_name' => '至尊披萨（东圃店）',
                'shop_address' => '天河区东圃大马路36号',
                'good_name' => '（超值餐）10英寸D24榴莲披萨',
                'commodity_price' => 0.01,
                'category_id' => 1,
                'cate_name' => '美食',
                'type' => 1,
                'selling_price' => 0.01,
                'good_integral' => 0,
                'attribute_id' => 4,
                'limit_num' => 2,
                'total_stock' => 300,
                'selling_num' => 30,
                'state' => 1,
                'order' => 100,
                'good_image' => 'http://img5.imgtn.bdimg.com/it/u=1218344908,2950045501&fm=26&gp=0.jpg',
                'detail_image' => 'http://img3.imgtn.bdimg.com/it/u=2136448882,2820293373&fm=26&gp=0.jpg',
                'description' => '购买须知描述',
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                'user_id' => 1,
                'username' => '舒婷',
                'shop_id' => 1,
                'shop_name' => '至尊披萨（东圃店）',
                'shop_address' => '天河区东圃大马路36号',
                'good_name' => '（超值餐B）10英寸榴莲披萨',
                'commodity_price' => 0.01,
                'category_id' => 1,
                'cate_name' => '美食',
                'type' => 2,
                'selling_price' => 0,
                'good_integral' => 39,
                'attribute_id' => 4,
                'limit_num' => 2,
                'total_stock' => 300,
                'selling_num' => 28,
                'state' => 1,
                'order' => 80,
                'good_image' => 'http://img5.imgtn.bdimg.com/it/u=1218344908,2950045501&fm=26&gp=0.jpg',
                'detail_image' => 'http://img3.imgtn.bdimg.com/it/u=2136448882,2820293373&fm=26&gp=0.jpg',
                'description' => '购买须知描述',
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                'user_id' => 1,
                'username' => '舒婷',
                'shop_id' => 1,
                'shop_name' => '至尊披萨（东圃店）',
                'shop_address' => '天河区东圃大马路36号',
                'good_name' => '8英寸新奥尔良烤鸡肉披萨 + 1瓶可口可乐',
                'commodity_price' => 40,
                'category_id' => 1,
                'cate_name' => '美食',
                'type' => 1,
                'selling_price' => 29.9,
                'good_integral' => 0,
                'attribute_id' => 4,
                'limit_num' => 10,
                'total_stock' => 300,
                'selling_num' => 35,
                'state' => 1,
                'order' => 100,
                'good_image' => 'http://img5.imgtn.bdimg.com/it/u=1218344908,2950045501&fm=26&gp=0.jpg',
                'detail_image' => 'http://img3.imgtn.bdimg.com/it/u=2136448882,2820293373&fm=26&gp=0.jpg',
                'description' => '购买须知描述',
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                'user_id' => 1,
                'username' => '舒婷',
                'shop_id' => 1,
                'shop_name' => '至尊披萨（东圃店）',
                'shop_address' => '天河区东圃大马路36号',
                'good_name' => '10英寸夏威夷披萨',
                'commodity_price' => 29.9,
                'category_id' => 1,
                'cate_name' => '美食',
                'type' => 2,
                'selling_price' => 29,
                'good_integral' => 0,
                'attribute_id' => 4,
                'limit_num' => 3,
                'total_stock' => 300,
                'selling_num' => 18,
                'state' => 1,
                'order' => 100,
                'good_image' => 'http://img5.imgtn.bdimg.com/it/u=1218344908,2950045501&fm=26&gp=0.jpg',
                'detail_image' => 'http://img3.imgtn.bdimg.com/it/u=2136448882,2820293373&fm=26&gp=0.jpg',
                'description' => '购买须知描述',
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                'user_id' => 2,
                'username' => '逍遥子',
                'shop_id' => 2,
                'shop_name' => '必胜客',
                'shop_address' => '车陂启明大街南三巷2号',
                'good_name' => '烤红薯',
                'commodity_price' => 9.9,
                'category_id' => 1,
                'cate_name' => '美食',
                'type' => 2,
                'selling_price' => 0,
                'good_integral' => 5,
                'attribute_id' => 4,
                'limit_num' => 3,
                'total_stock' => 200,
                'selling_num' => 26,
                'state' => 1,
                'order' => 100,
                'good_image' => 'http://img5.imgtn.bdimg.com/it/u=1218344908,2950045501&fm=26&gp=0.jpg',
                'detail_image' => 'http://img3.imgtn.bdimg.com/it/u=2136448882,2820293373&fm=26&gp=0.jpg',
                'description' => '购买须知描述',
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                'user_id' => 2,
                'username' => '逍遥子',
                'shop_id' => 2,
                'shop_name' => '库克石烧',
                'shop_address' => '车陂启明大街南三巷2号',
                'good_name' => '雪花牛排',
                'commodity_price' => 69.9,
                'category_id' => 1,
                'cate_name' => '美食',
                'type' => 2,
                'selling_price' => 0,
                'good_integral' => 100,
                'attribute_id' => 4,
                'limit_num' => 3,
                'total_stock' => 100,
                'selling_num' => 13,
                'state' => 1,
                'order' => 100,
                'good_image' => 'http://img5.imgtn.bdimg.com/it/u=1218344908,2950045501&fm=26&gp=0.jpg',
                'detail_image' => 'http://img3.imgtn.bdimg.com/it/u=2136448882,2820293373&fm=26&gp=0.jpg',
                'description' => '购买须知描述',
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
        ]);
    }
}
