<?php

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;
class GoodCartsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('good_carts')->insert([
            [
                'good_id' => 5,
                'user_id' => 1,
                'shop_id' => 1,
                'cart_num' => 3,
                'good_name' => '榴莲披萨',
                'good_image' => 'http://img5.imgtn.bdimg.com/it/u=1218344908,2950045501&fm=26&gp=0.jpg',
                'money' => 68,
                'credit' => 0,
                'orgin_money' => 3,
                'good_type' => 1,
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                'good_id' => 5,
                'user_id' => 1,
                'shop_id' => 2,
                'cart_num' => 2,
                'good_name' => '榴莲披萨',
                'good_image' => 'http://img5.imgtn.bdimg.com/it/u=1218344908,2950045501&fm=26&gp=0.jpg',
                'money' => 38,
                'credit' => 0,
                'orgin_money' => 3,
                'good_type' => 1,
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                'good_id' => 1,
                'user_id' => 1,
                'shop_id' => 2,
                'cart_num' => 5,
                'good_name' => '榴莲披萨',
                'good_image' => 'http://img5.imgtn.bdimg.com/it/u=1218344908,2950045501&fm=26&gp=0.jpg',
                'money' => 18,
                'credit' => 0,
                'orgin_money' => 3,
                'good_type' => 1,
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                'good_id' => 1,
                'user_id' => 1,
                'shop_id' => 1,
                'cart_num' => 3,
                'good_name' => '榴莲披萨',
                'good_image' => 'http://img5.imgtn.bdimg.com/it/u=1218344908,2950045501&fm=26&gp=0.jpg',
                'money' => 0,
                'credit' => 15,
                'orgin_money' => 3,
                'good_type' => 2,
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                'good_id' => 2,
                'user_id' => 1,
                'shop_id' => 1,
                'cart_num' => 8,
                'good_name' => '榴莲披萨',
                'good_image' => 'http://img5.imgtn.bdimg.com/it/u=1218344908,2950045501&fm=26&gp=0.jpg',
                'money' => 0,
                'credit' => 30,
                'orgin_money' => 5,
                'good_type' => 2,
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                'good_id' => 2,
                'user_id' => 1,
                'shop_id' => 1,
                'cart_num' => 3,
                'good_name' => '榴莲披萨',
                'good_image' => 'http://img5.imgtn.bdimg.com/it/u=1218344908,2950045501&fm=26&gp=0.jpg',
                'money' => 68,
                'credit' => 0,
                'orgin_money' => 3,
                'good_type' => 1,
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                'good_id' => 3,
                'user_id' => 1,
                'shop_id' => 2,
                'cart_num' => 2,
                'good_name' => '榴莲披萨',
                'good_image' => 'http://img5.imgtn.bdimg.com/it/u=1218344908,2950045501&fm=26&gp=0.jpg',
                'money' => 68,
                'credit' => 0,
                'orgin_money' => 3,
                'good_type' => 1,
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                'good_id' => 3,
                'user_id' => 1,
                'shop_id' => 2,
                'cart_num' => 1,
                'good_name' => '榴莲披萨',
                'good_image' => 'http://img5.imgtn.bdimg.com/it/u=1218344908,2950045501&fm=26&gp=0.jpg',
                'money' => 68,
                'credit' => 0,
                'orgin_money' => 3,
                'good_type' => 1,
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                'good_id' => 4,
                'user_id' => 1,
                'shop_id' => 1,
                'cart_num' => 3,
                'good_name' => '榴莲披萨',
                'good_image' => 'http://img5.imgtn.bdimg.com/it/u=1218344908,2950045501&fm=26&gp=0.jpg',
                'money' => 68,
                'credit' => 0,
                'orgin_money' => 3,
                'good_type' => 1,
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                'good_id' => 4,
                'user_id' => 1,
                'shop_id' => 1,
                'cart_num' => 2,
                'good_name' => '榴莲披萨',
                'good_image' => 'http://img5.imgtn.bdimg.com/it/u=1218344908,2950045501&fm=26&gp=0.jpg',
                'money' => 68,
                'credit' => 0,
                'orgin_money' => 3,
                'good_type' => 1,
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
        ]);
    }
}
