<?php

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;
class MemberBindsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('member_binds')->insert([
            [
                'user_id' => 1,
                'nick_name' => '中神通',
                'avatar' => 'http://img3.imgtn.bdimg.com/it/u=3527936276,4134359723&fm=11&gp=0.jpg',
                'user_signature' => '学习使我快乐',
                'invite_code' => 666888,
                'pay_password' => bcrypt('123456'),
                'username' => '苏雅',
                'code_sn' => '441224199508180618',
                'sex' => 2,
                'front_card_image' => 'http://meituyuan.com/data/share/2014/08/6/02102053dc4b03270d9_b.jpg',
                'back_card_image' => 'http://meituyuan.com/data/share/2014/08/6/02102053dc4b03270d9_b.jpg',
                'check_status' => 20,
                'bind_card_status' => 20,
                'address' => '广州市海珠区',
                'province' => '广东省',
                'city' => '广州市',
                'district' => '海珠区',
                'address_detail' => '广州市海珠区客村街道28号',
                'num' => 5,
                'login_ip' => '127.0.0.1',
                'login_time' =>  date('Y-m-d H:i:s'),
                'expire_time' => 1,
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                'user_id' => 2,
                'nick_name' => '杀神一刀斩',
                'avatar' => 'http://img3.imgtn.bdimg.com/it/u=3527936276,4134359723&fm=11&gp=0.jpg',
                'user_signature' => '人间不值得',
                'invite_code' => 123456,
                'pay_password' => bcrypt('123456'),
                'username' => '杀神',
                'code_sn' => '441224199508180618',
                'sex' => 1,
                'front_card_image' => 'http://meituyuan.com/data/share/2014/08/6/02102053dc4b03270d9_b.jpg',
                'back_card_image' => 'http://meituyuan.com/data/share/2014/08/6/02102053dc4b03270d9_b.jpg',
                'check_status' => 20,
                'bind_card_status' => 20,
                'address' => '广州市海珠区',
                'province' => '广东省',
                'city' => '广州市',
                'district' => '天河区',
                'address_detail' => '车陂启明大街30号',
                'num' => 3,
                'login_ip' => '127.0.0.1',
                'login_time' =>  date('Y-m-d H:i:s'),
                'expire_time' => 1,
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                'user_id' => 3,
                'nick_name' => '赤帝',
                'avatar' => 'http://img3.imgtn.bdimg.com/it/u=3527936276,4134359723&fm=11&gp=0.jpg',
                'user_signature' => '血海滔滔，赤帝东来',
                'invite_code' => 123456,
                'pay_password' => bcrypt('123456'),
                'username' => '海东来',
                'code_sn' => '441224199508180618',
                'sex' => 1,
                'front_card_image' => 'http://meituyuan.com/data/share/2014/08/6/02102053dc4b03270d9_b.jpg',
                'back_card_image' => 'http://meituyuan.com/data/share/2014/08/6/02102053dc4b03270d9_b.jpg',
                'check_status' => 20,
                'bind_card_status' => 20,
                'address' => '广州市海珠区',
                'province' => '广东省',
                'city' => '广州市',
                'district' => '天河区',
                'address_detail' => '黄村西路18号',
                'num' => 3,
                'login_ip' => '127.0.0.1',
                'login_time' =>  date('Y-m-d H:i:s'),
                'expire_time' => 1,
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                'user_id' => 4,
                'nick_name' => '乔峰',
                'avatar' => 'http://img3.imgtn.bdimg.com/it/u=3527936276,4134359723&fm=11&gp=0.jpg',
                'user_signature' => '血海滔滔，赤帝东来啦',
                'invite_code' => 123456,
                'pay_password' => bcrypt('123456'),
                'username' => '海东来',
                'code_sn' => '441224199508180618',
                'sex' => 1,
                'front_card_image' => 'http://meituyuan.com/data/share/2014/08/6/02102053dc4b03270d9_b.jpg',
                'back_card_image' => 'http://meituyuan.com/data/share/2014/08/6/02102053dc4b03270d9_b.jpg',
                'check_status' => 20,
                'bind_card_status' => 20,
                'address' => '广州市海珠区',
                'province' => '广东省',
                'city' => '广州市',
                'district' => '天河区',
                'address_detail' => '黄村西路18号',
                'num' => 3,
                'login_ip' => '127.0.0.1',
                'login_time' =>  date('Y-m-d H:i:s'),
                'expire_time' => 1,
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                'user_id' => 5,
                'nick_name' => '虚竹',
                'avatar' => 'http://img3.imgtn.bdimg.com/it/u=3527936276,4134359723&fm=11&gp=0.jpg',
                'user_signature' => '血海滔滔，赤帝东来。。。',
                'invite_code' => 123456,
                'pay_password' => bcrypt('123456'),
                'username' => '海东来',
                'code_sn' => '441224199508180618',
                'sex' => 1,
                'front_card_image' => 'http://meituyuan.com/data/share/2014/08/6/02102053dc4b03270d9_b.jpg',
                'back_card_image' => 'http://meituyuan.com/data/share/2014/08/6/02102053dc4b03270d9_b.jpg',
                'check_status' => 20,
                'bind_card_status' => 20,
                'address' => '广州市海珠区',
                'province' => '广东省',
                'city' => '广州市',
                'district' => '天河区',
                'address_detail' => '黄村西路18号',
                'num' => 3,
                'login_ip' => '127.0.0.1',
                'login_time' =>  date('Y-m-d H:i:s'),
                'expire_time' => 1,
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
        ]);
    }
}
