<?php

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;
class OrderItemsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('order_items')->insert([
            [
                'order_id' => 1,
                'user_id' => 1,
                'username' => '舒婷',
                'good_image' => 'http://img2.imgtn.bdimg.com/it/u=3615796477,1957332095&fm=26&gp=0.jpg',
                'good_name' => '（点披萨送小吃）10英寸金枕榴莲果肉披萨',
                'good_price' => 36.9,
                'amount' => 1,
                'total_price' => 36.9,
                'good_type' => 10,
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                'order_id' => 1,
                'user_id' => 1,
                'username' => '舒婷',
                'good_image' => 'http://img2.imgtn.bdimg.com/it/u=3615796477,1957332095&fm=26&gp=0.jpg',
                'good_name' => '超爱至尊2人套餐B',
                'good_price' => 96,
                'amount' => 1,
                'total_price' => 96,
                'good_type' => 20,
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                'order_id' => 1,
                'user_id' => 1,
                'username' => '舒婷',
                'good_image' => 'http://img2.imgtn.bdimg.com/it/u=3615796477,1957332095&fm=26&gp=0.jpg',
                'good_name' => '脆皮香蕉',
                'good_price' => 3.5,
                'amount' => 2,
                'total_price' => 7,
                'good_type' => 10,
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],

            [
                'order_id' => 2,
                'user_id' => 1,
                'username' => '舒婷',
                'good_image' => 'http://img2.imgtn.bdimg.com/it/u=3615796477,1957332095&fm=26&gp=0.jpg',
                'good_name' => '（点披萨送小吃）10英寸金枕榴莲果肉披萨',
                'good_price' => 36.9,
                'amount' => 1,
                'total_price' => 36.9,
                'good_type' => 10,
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                'order_id' => 2,
                'user_id' => 1,
                'username' => '舒婷',
                'good_image' => 'http://img2.imgtn.bdimg.com/it/u=3615796477,1957332095&fm=26&gp=0.jpg',
                'good_name' => '超爱至尊2人套餐B',
                'good_price' => 96,
                'amount' => 1,
                'total_price' => 96,
                'good_type' => 20,
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                'order_id' => 2,
                'user_id' => 1,
                'username' => '舒婷',
                'good_image' => 'http://img2.imgtn.bdimg.com/it/u=3615796477,1957332095&fm=26&gp=0.jpg',
                'good_name' => '脆皮香蕉',
                'good_price' => 3.5,
                'amount' => 2,
                'total_price' => 7,
                'good_type' => 10,
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],

            [
                'order_id' => 3,
                'user_id' => 1,
                'username' => '舒婷',
                'good_image' => 'http://img2.imgtn.bdimg.com/it/u=3615796477,1957332095&fm=26&gp=0.jpg',
                'good_name' => '（点披萨送小吃）10英寸金枕榴莲果肉披萨',
                'good_price' => 36.9,
                'amount' => 1,
                'total_price' => 36.9,
                'good_type' => 10,
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                'order_id' => 3,
                'user_id' => 1,
                'username' => '舒婷',
                'good_image' => 'http://img2.imgtn.bdimg.com/it/u=3615796477,1957332095&fm=26&gp=0.jpg',
                'good_name' => '超爱至尊2人套餐B',
                'good_price' => 96,
                'amount' => 1,
                'total_price' => 96,
                'good_type' => 20,
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                'order_id' => 3,
                'user_id' => 1,
                'username' => '舒婷',
                'good_image' => 'http://img2.imgtn.bdimg.com/it/u=3615796477,1957332095&fm=26&gp=0.jpg',
                'good_name' => '脆皮香蕉',
                'good_price' => 3.5,
                'amount' => 2,
                'total_price' => 7,
                'good_type' => 10,
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],

            [
                'order_id' => 4,
                'user_id' => 1,
                'username' => '舒婷',
                'good_image' => 'http://img2.imgtn.bdimg.com/it/u=3615796477,1957332095&fm=26&gp=0.jpg',
                'good_name' => '（点披萨送小吃）10英寸金枕榴莲果肉披萨',
                'good_price' => 36.9,
                'amount' => 1,
                'total_price' => 36.9,
                'good_type' => 10,
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                'order_id' => 4,
                'user_id' => 1,
                'username' => '舒婷',
                'good_image' => 'http://img2.imgtn.bdimg.com/it/u=3615796477,1957332095&fm=26&gp=0.jpg',
                'good_name' => '超爱至尊2人套餐B',
                'good_price' => 96,
                'amount' => 1,
                'total_price' => 96,
                'good_type' => 20,
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                'order_id' => 4,
                'user_id' => 1,
                'username' => '舒婷',
                'good_image' => 'http://img2.imgtn.bdimg.com/it/u=3615796477,1957332095&fm=26&gp=0.jpg',
                'good_name' => '脆皮香蕉',
                'good_price' => 3.5,
                'amount' => 2,
                'total_price' => 7,
                'good_type' => 10,
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],

            [
                'order_id' => 5,
                'user_id' => 1,
                'username' => '舒婷',
                'good_image' => 'http://img2.imgtn.bdimg.com/it/u=3615796477,1957332095&fm=26&gp=0.jpg',
                'good_name' => '（点披萨送小吃）10英寸金枕榴莲果肉披萨',
                'good_price' => 36.9,
                'amount' => 1,
                'total_price' => 36.9,
                'good_type' => 10,
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                'order_id' => 5,
                'user_id' => 1,
                'username' => '舒婷',
                'good_image' => 'http://img2.imgtn.bdimg.com/it/u=3615796477,1957332095&fm=26&gp=0.jpg',
                'good_name' => '超爱至尊2人套餐B',
                'good_price' => 96,
                'amount' => 1,
                'total_price' => 96,
                'good_type' => 20,
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                'order_id' => 5,
                'user_id' => 1,
                'username' => '舒婷',
                'good_image' => 'http://img2.imgtn.bdimg.com/it/u=3615796477,1957332095&fm=26&gp=0.jpg',
                'good_name' => '脆皮香蕉',
                'good_price' => 3.5,
                'amount' => 2,
                'total_price' => 7,
                'good_type' => 10,
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
        ]);
    }
}
